apiVersion: apps/v1
kind: Deployment
metadata:
  name: fly-island-app
spec:
  selector:
    matchLabels:
      app: fly-island-app
  replicas: 3
  template:
    metadata:
      labels:
        app: fly-island-app
    spec:
      containers:
      - name: fly-island-app
        image: gcr.io/${{ secrets.GCP_PROJECT_ID }}/flies:${GITHUB_SHA}
        ports:
        - containerPort: 8080
        env:
        - name: DATABASE_URI
          value: "postgresql://postgres:password@fly-island:us-central1:field-of-flowers:5432/field-of-flowers"
        - name: GOOGLE_CLOUD_PROJECT
          value: "fly-island"
        - name: GOOGLE_APPLICATION_CREDENTIALS
          valueFrom:
            secretKeyRef:
              name: gcp-credentials
              key: service-account.json #Replace with the correct key name
---
apiVersion: v1
kind: Service
metadata:
  name: fly-island-app-service
spec:
  selector:
    app: fly-island-app
  type: LoadBalancer # Or NodePort depending on your GKE setup
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080
