name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v0
        with:
          credentials_json: ${{ secrets.GCP_SA_GH_SECRET }} # Use the service account key

      - name: Build and push Docker image
        run: |
          docker build -t gcr.io/${{ secrets.GCP_PROJECT_ID }}/flies:$GITHUB_SHA .
          docker push gcr.io/${{ secrets.GCP_PROJECT_ID }}/flies:$GITHUB_SHA

      - name: Create artifacts directory
        run: mkdir -p ./artifacts

      - name: Copy artifacts
        run: cp -r ./some/path/to/your/artifacts/* ./artifacts

      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: flies-artifacts-${{ github.sha }}
          path: ./artifacts
          if-no-files-found: error  # Fail if no artifacts are found
      
      - name: Deploy to GKE
        run: |
          kubectl apply -f deployment.yaml

      - name: Trigger pipeline status update
        run: |
          curl -X POST http://$(kubectl get service fly-island-app-service -o jsonpath='{.status.loadBalancer.ingress[0].ip}'):8080/update_pipeline_status


# docker build -t gcr.io/your-project-id/your-app-name:v1 .
# docker push gcr.io/your-project-id/your-app-name:v1
